### ISSUE TITLE
[SKPersistor] faciliter la persistence des Int, Float, Long et boolean

### ISSUE THREAD

**Issue by sgueniot-ua** [skot-framework/skot#1]
Actuellement il est possible de mettre directement des String et des objets serializable dans un persistor. Il serait pratique que ce le soit aussi pour les Int, les Float, les Long et les boolean, comme c'est le cas des preferences android.

**Comment by MathieuScotet** [comment]
Traité par le commit 808a19b56c103a8d7acbc294973b32a6720f361b
Disponible depuis la version 1.0.0-alpha58
